[tox]
requires =
    tox-uv
env_list =
    py39-test-resource-detector-oldest
    py310-test-resource-detector-{latest,oldest}
    py311-test-resource-detector-{latest,oldest}
    py312-test-resource-detector-latest
    py313-test-resource-detector-latest
    lint-resource-detector
    typecheck
    docs

[testenv]
package = skip

[testenv:py{39,310,311,312,313}-test-resource-detector-{latest,oldest}]
deps =
    latest: -r {toxinidir}/opentelemetry-resource-detector-ray/test-requirements-latest.txt
    oldest: -r {toxinidir}/opentelemetry-resource-detector-ray/test-requirements-oldest.txt
commands =
    pytest {toxinidir}/opentelemetry-resource-detector-ray/tests {posargs}

[testenv:lint-resource-detector]
deps =
    pylint
    -e {toxinidir}/opentelemetry-resource-detector-ray[detects]
commands =
    pylint {toxinidir}/opentelemetry-resource-detector-ray/src/opentelemetry {posargs}

[testenv:typecheck]
deps =
  pyright
  -e {toxinidir}/opentelemetry-resource-detector-ray[detects]

commands =
  pyright

[testenv:docs]
recreate = True
deps =
  -r {toxinidir}/docs-requirements.txt
  -e {toxinidir}/opentelemetry-resource-detector-ray[detects]
changedir = docs
commands =
  sphinx-build -E -a -W -b html -T . _build/html
