name: Publish Adhoc

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package directory to publish
        required: true
        type: choice
        options:
          - opentelemetry-resource-detector-ray

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build
        run: pip install build

      - name: Build package
        run: python -m build ${{ inputs.package }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ inputs.package }}/dist/
